# Generated by Django 6.1.1 on 2026-09-30 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
